// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP40_aMXW944p1OchebgN7p1X9f1Hv7pQ',
    appId: '1:1021660422413:web:14d7291bb12f1fc5b29044',
    messagingSenderId: '1021660422413',
    projectId: 'chamcongclb-spit',
    authDomain: 'chamcongclb-spit.firebaseapp.com',
    storageBucket: 'chamcongclb-spit.firebasestorage.app',
    measurementId: 'G-PWFDED3DJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7uywu5hpe0_8l5TFvpbXQFxjSiSi8DEw',
    appId: '1:1021660422413:android:353d39b851c797eeb29044',
    messagingSenderId: '1021660422413',
    projectId: 'chamcongclb-spit',
    storageBucket: 'chamcongclb-spit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNVYQxXfImRvHaPwz1zv0uH5lRHXZ9GHA',
    appId: '1:1021660422413:ios:107220e3f755806cb29044',
    messagingSenderId: '1021660422413',
    projectId: 'chamcongclb-spit',
    storageBucket: 'chamcongclb-spit.firebasestorage.app',
    iosBundleId: 'com.example.chamcongspitFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNVYQxXfImRvHaPwz1zv0uH5lRHXZ9GHA',
    appId: '1:1021660422413:ios:107220e3f755806cb29044',
    messagingSenderId: '1021660422413',
    projectId: 'chamcongclb-spit',
    storageBucket: 'chamcongclb-spit.firebasestorage.app',
    iosBundleId: 'com.example.chamcongspitFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP40_aMXW944p1OchebgN7p1X9f1Hv7pQ',
    appId: '1:1021660422413:web:9a5ca5e1e10aa371b29044',
    messagingSenderId: '1021660422413',
    projectId: 'chamcongclb-spit',
    authDomain: 'chamcongclb-spit.firebaseapp.com',
    storageBucket: 'chamcongclb-spit.firebasestorage.app',
    measurementId: 'G-246MJDHWYP',
  );
}
